name = "ziSurv"
author = "null2264"
version = "0.0.1"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7f13d3e273937055ff8220bf647a79dacdf845685085fefaae6ab0bd61059203"

[versions]
fabric = "0.12.3"
minecraft = "1.17.1"
